SELECTED_BG = "#000000"
SELECTED_FG = "#FFFF55"
IDLE_BG = "#FFFFFF"
IDLE_FG = "#000000"

ON_MOUSE_BG = "gray"
ON_MOUSE_FG = "black"

'''Translation frame colors definitions'''
TRANS_SELECTED_BG = "#000000"
TRANS_SELECTED_FG = "#FFFFFF"
TRANS_IDLE_BG = "#DFD4C9"
TRANS_IDLE_FG = "#000000"

'''Lesson Editor Color Definition'''

LESSON_SELECTED_BG = "#000000"
LESSON_SELECTED_FG = "#FFFFFF"
LESSON_IDLE_BG = "#FFFFFF"
LESSON_IDLE_FG = "#000000"

TYPE_NORMAL = '#AAAAFF'
TYPE_LETTER = '#FFAAAA'
TYPE_POETRY = '#AAFFAA'
TYPE_DIALOG = '#AAFFFF'

BUTTON_SELECTED = '#88FFFF'
BUTTON_NOT_SELECTED = '#BBBBBB'

CHOICE_INCORRECT = '#FD5A5A'
CHOICE_CORRECT = '#53F268'
LIGHT_GREEN = "#C8F990"
LIGHT_YELLOW = "#F9F58E"
LIGHT_GREEN_BLUE = "#97D08C"
LIGHT_PURPLE = "#E2C5DA"
